apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-mongo-depl
  labels:
    app: posts-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts-mongodb
  template:
    metadata:
      labels:
        app: posts-mongodb
    spec:
      containers:
      - name: posts-mongodb
        image: mongo
        resources:
          limits:
            cpu: "100m"
            memory: "128Mi"
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: posts-mongo-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: posts-mongo-secret
              key: MONGO_ROOT_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: posts-mongo-service
spec:
  selector:
    app: posts-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
