apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
  labels:
    app: posts-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: posts-service
  template:
    metadata:
      labels:
        app: posts-service
    spec:
      containers:
      - name: kubmic-posts
        image: awesomelike/kubmic-posts
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 50051
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: posts-mongo-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGODB_PASS
          valueFrom:
            secretKeyRef:
              name: posts-mongo-secret
              key: MONGO_ROOT_PASSWORD
        - name: MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: posts-configmap
              key: MONGO_SERVER
        - name: GRPC_HOST
          valueFrom:
            configMapKeyRef:
              name: posts-configmap
              key: GRPC_HOST
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: posts-configmap
              key: GRPC_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: posts-service
spec:
  selector:
    app: posts-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      # nodePort: 30001
              

        