apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-depl
  labels:
    app: users-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
      - name: kubmic-users
        image: awesomelike/kubmic-users
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"
        ports:
        - containerPort: 50051
        env:
        - name: MONGODB_USER
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: MONGO_ROOT_USERNAME
        - name: MONGODB_PASS
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: MONGO_ROOT_PASSWORD
        - name: MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: users-configmap
              key: MONGO_SERVER
        - name: GRPC_HOST
          valueFrom:
            configMapKeyRef:
              name: users-configmap
              key: GRPC_HOST
        - name: GRPC_PORT
          valueFrom:
            configMapKeyRef:
              name: users-configmap
              key: GRPC_PORT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: users-secret
              key: JWT_SECRET
        - name: JWT_EXPIRATION
          valueFrom:
            configMapKeyRef:
              name: users-configmap
              key: JWT_EXPIRATION
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users-service
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
      # nodePort: 30000
              

        