name: Docker build and update images on the registry

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUN_NUMBER: ${{ github.run_number }}
    steps:
      - uses: actions/checkout@v2
      
      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
      - name: Build users service
        run: |
          docker build -t awesomelike/kubmic-users:$RUN_NUMBER ./userService

      - name: Build posts service
        run: |
          docker build -t awesomelike/kubmic-posts:$RUN_NUMBER ./postService
      
      - name: Build rest proxy service
        run: |
          docker build -t awesomelike/kubmic-restproxy:$RUN_NUMBER ./restProxy
      
      - name: Push images to the registry
        run: |
          docker push awesomelike/kubmic-users:$RUN_NUMBER
          docker push awesomelike/kubmic-posts:$RUN_NUMBER
          docker push awesomelike/kubmic-restproxy:$RUN_NUMBER
